### ISSUE TITLE
没法正常打包

### ISSUE THREAD

**Issue by leonzhuhi** [heiBin/RobuFix#1]
执行正常的 打包 gradlew aR,报错

* What went wrong:
Execution failed for task ':app:prepareReleaseInject'.
> Bad <init> method call from inside of a branch
Exception Details:
  Location:
    com/duoyi/gradle/RobuClassPackVisitor$ISVisitor.<init>(Lcom/duoyi/gradle/RobuClassPackVisitor;ILorg/objectweb/asm/MethodVisitor;ILjava/lang/Strin
g;Ljava/lang/String;)V @146: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b800 193a 072b 3a08 1908 2a5f b500 1b19
    0x0000010: 0857 08bd 001d 5903 1cb8 0023 5359 042d
    0x0000020: 5359 0515 04b8 0023 5359 0619 0553 5907
    0x0000030: 1906 5359 10ff 1204 b800 292a 5fab 0000
    0x0000040: 0000 00f8 0000 0004 8a43 823f 0000 002b
    0x0000050: dafc 5eeb 0000 005b 2d06 d2b1 0000 0099
    0x0000060: 5473 3638 0000 00c1 5f5a 5903 3212 2bb8
    0x0000070: 002f c000 2b5f 5904 32b8 0035 5f59 0532
    0x0000080: b800 3bc0 003d 5f59 0632 b800 3bc0 003d
    0x0000090: 5f57 b700 40a7 00aa 5f5a 5903 32b8 0035
    0x00000a0: 5f59 0432 1242 b800 2fc0 0042 5f59 0532
    0x00000b0: b800 3bc0 003d 5f59 0632 1244 b800 2fc0
    0x00000c0: 0044 5f59 0732 1246 b800 2fc0 0046 5f57
    0x00000d0: b700 49a7 006c 5f5a 5903 32b8 0035 5f59
    0x00000e0: 0432 1242 b800 2fc0 0042 5f59 0532 122b
    0x00000f0: b800 2fc0 002b 5f57 b700 4ca7 0044 5f5a
    0x0000100: 5903 32b8 0035 5f59 0432 122b b800 2fc0
    0x0000110: 002b 5f59 0532 b800 355f 5906 32b8 003b
    0x0000120: c000 3d5f 5907 32b8 003b c000 3d5f 57b7
    0x0000130: 004f a700 0dbb 0051 5912 53b7 0056 bf57
    0x0000140: 2ab6 005a 3a09 1909 2a5f b500 5c19 0957
    0x0000150: 1907 125d 322a 1905 1906 b900 6304 003a
    0x0000160: 0a19 0a12 65b8 002f c000 652a 5fb5 0067
    0x0000170: 190a 57b1
  Stackmap Table:
    full_frame(@104,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@152,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@214,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@254,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@309,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@319,{Object[#2],Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120]})

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:prepareReleaseInject'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    com/duoyi/gradle/RobuClassPackVisitor$ISVisitor.<init>(Lcom/duoyi/gradle/RobuClassPackVisitor;ILorg/objectweb/asm/MethodVisitor;ILjava/lang/Strin
g;Ljava/lang/String;)V @146: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b800 193a 072b 3a08 1908 2a5f b500 1b19
    0x0000010: 0857 08bd 001d 5903 1cb8 0023 5359 042d
    0x0000020: 5359 0515 04b8 0023 5359 0619 0553 5907
    0x0000030: 1906 5359 10ff 1204 b800 292a 5fab 0000
    0x0000040: 0000 00f8 0000 0004 8a43 823f 0000 002b
    0x0000050: dafc 5eeb 0000 005b 2d06 d2b1 0000 0099
    0x0000060: 5473 3638 0000 00c1 5f5a 5903 3212 2bb8
    0x0000070: 002f c000 2b5f 5904 32b8 0035 5f59 0532
    0x0000080: b800 3bc0 003d 5f59 0632 b800 3bc0 003d
    0x0000090: 5f57 b700 40a7 00aa 5f5a 5903 32b8 0035
    0x00000a0: 5f59 0432 1242 b800 2fc0 0042 5f59 0532
    0x00000b0: b800 3bc0 003d 5f59 0632 1244 b800 2fc0
    0x00000c0: 0044 5f59 0732 1246 b800 2fc0 0046 5f57
    0x00000d0: b700 49a7 006c 5f5a 5903 32b8 0035 5f59
    0x00000e0: 0432 1242 b800 2fc0 0042 5f59 0532 122b
    0x00000f0: b800 2fc0 002b 5f57 b700 4ca7 0044 5f5a
    0x0000100: 5903 32b8 0035 5f59 0432 122b b800 2fc0
    0x0000110: 002b 5f59 0532 b800 355f 5906 32b8 003b
    0x0000120: c000 3d5f 5907 32b8 003b c000 3d5f 57b7
    0x0000130: 004f a700 0dbb 0051 5912 53b7 0056 bf57
    0x0000140: 2ab6 005a 3a09 1909 2a5f b500 5c19 0957
    0x0000150: 1907 125d 322a 1905 1906 b900 6304 003a
    0x0000160: 0a19 0a12 65b8 002f c000 652a 5fb5 0067
    0x0000170: 190a 57b1
  Stackmap Table:
    full_frame(@104,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@152,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@214,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@254,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@309,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@319,{Object[#2],Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120]})

        at com.duoyi.gradle.RobuClassPackVisitor.visitMethod(RobuClassPackVisitor.groovy:47)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:722)
        at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412)
        at org.objectweb.asm.tree.ClassNode$accept.call(Unknown Source)
        at com.duoyi.gradle.RobuInject.referHackWhenInit(RobuInject.groovy:121)
        at com.duoyi.gradle.RobuInject.processClass(RobuInject.groovy:97)
        at com.duoyi.gradle.RobuInject$_injectDir_closure1.doCall(RobuInject.groovy:83)
        at com.duoyi.gradle.RobuInject.injectDir(RobuInject.groovy:64)
        at com.duoyi.gradle.RobuInject$injectDir.call(Unknown Source)
        at com.duoyi.gradle.RobuPlugin$_apply_closure1$_closure2$_closure4$_closure8.doCall(RobuPlugin.groovy:89)
        at com.duoyi.gradle.RobuPlugin$_apply_closure1$_closure2$_closure4.doCall(RobuPlugin.groovy:58)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more

BUILD FAILED

Total time: 8.202 secs

E:\project\RobuFix-master>gradlew aR
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.14.1/userguide/gradle
_daemon.html.
:buildsrc:compileJava UP-TO-DATE                        
:buildsrc:compileGroovy UP-TO-DATE
:buildsrc:processResources UP-TO-DATE
:buildsrc:classes UP-TO-DATE
:buildsrc:jar UP-TO-DATE
:buildsrc:assemble UP-TO-DATE
:buildsrc:compileTestJava UP-TO-DATE
:buildsrc:compileTestGroovy UP-TO-DATE
:buildsrc:processTestResources UP-TO-DATE
:buildsrc:testClasses UP-TO-DATE
:buildsrc:test UP-TO-DATE
:buildsrc:check UP-TO-DATE
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:442)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
        at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.duoyi.gradle.RobuPlugin$_apply_closure1.doCall(RobuPlugin.groovy:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
        at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:40)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at com.duoyi.gradle.RobuInject$injectDir.call(Unknown Source)
itializedThis})
    full_frame(@254,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@309,{UninitializedThis,Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120],Unin
itializedThis})
    full_frame(@319,{Object[#2],Object[#116],Integer,Object[#43],Integer,Object[#61],Object[#61],Object[#118],Object[#116]},{Object[#120]})

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by heiBin** [comment]
你好，可以提供下编译环境的jdk版本和gradle plugin版本吗

**Comment by heiBin** [comment]
@leonzhuhi 或者你尝试换一下jdk版本再试下
